services:

  mysql:
    image: mysql:8.4
    container_name: tuctapi-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - tuctapi-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tuctapi-api
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      SWAGGER_ENABLED: ${SWAGGER_ENABLED}
    depends_on:
      - mysql
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - tuctapi-network

volumes:
  mysql_data:

networks:
  tuctapi-network:
    driver: bridge