name: Deploy TuctAPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy na VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          port: 22022
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/apps/tuctapi

            echo "Atualizando código..."
            git pull origin main

            echo "Recriando imagem..."
            docker compose build

            echo "Subindo nova versão..."
            docker compose up -d

            echo "Status dos containers:"
            docker compose ps