name: Deploy TuctAPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy na VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          port: 22022
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            set -e

            cd /opt/apps/tuctapi

            echo "================================="
            echo "Atualizando código..."
            echo "================================="

            git pull origin main

            echo "================================="
            echo "Construindo nova imagem..."
            echo "================================="

            docker compose build --no-cache api

            echo "================================="
            echo "Subindo nova versão..."
            echo "================================="

            docker compose up -d

            echo "================================="
            echo "Status dos containers"
            echo "================================="

            docker compose ps

            echo "================================="
            echo "Últimos logs da API"
            echo "================================="

            docker compose logs --tail=30 api